{
  "openapi": "3.1.0",
  "servers": [
    {
      "url": "https://github.com/samchon/nestia",
      "description": "insert your server url"
    }
  ],
  "info": {
    "version": "1.0.0",
    "title": "@samchon/nestia-test",
    "description": "Test program of Nestia",
    "license": {
      "name": "MIT"
    }
  },
  "paths": {
    "/exception/{section}/typed": {
      "post": {
        "tags": [],
        "parameters": [
          {
            "name": "section",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IBbsArticle.IStore"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IBbsArticle"
                }
              }
            }
          },
          "400": {
            "description": "invalid request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TypeGuardErrorany"
                },
                "example": {
                  "name": "BadRequestException",
                  "method": "TypedBody",
                  "path": "$input.title",
                  "expected": "string",
                  "value": 123,
                  "message": "invalid type"
                },
                "examples": {
                  "title": {
                    "summary": "title",
                    "description": "Wrong type of the title",
                    "value": {
                      "name": "BadRequestException",
                      "method": "TypedBody",
                      "path": "$input.title",
                      "expected": "string",
                      "value": 123,
                      "message": "invalid type"
                    }
                  },
                  "content": {
                    "summary": "content",
                    "description": "content of the article",
                    "value": {
                      "name": "BadRequestException",
                      "method": "TypedBody",
                      "path": "$input.title",
                      "expected": "string",
                      "value": 123,
                      "message": "invalid type"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "unable to find the matched section",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/INotFound"
                }
              }
            }
          },
          "428": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IUnprocessibleEntity"
                }
              }
            }
          },
          "5XX": {
            "description": "internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IInternalServerError"
                }
              }
            }
          }
        },
        "x-samchon-accessor": [
          "exception",
          "typed"
        ],
        "x-samchon-controller": "ExceptionController"
      }
    },
    "/exception/{section}/union": {
      "get": {
        "tags": [],
        "parameters": [
          {
            "name": "section",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/INotFound"
                    },
                    {
                      "$ref": "#/components/schemas/IUnprocessibleEntity"
                    },
                    {
                      "$ref": "#/components/schemas/IBbsArticle"
                    }
                  ]
                }
              }
            }
          },
          "428": {
            "description": "unable to process the request",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/IExceptional.Something"
                    },
                    {
                      "$ref": "#/components/schemas/IExceptional.Nothing"
                    },
                    {
                      "$ref": "#/components/schemas/IExceptional.Everything"
                    }
                  ]
                }
              }
            }
          }
        },
        "x-samchon-accessor": [
          "exception",
          "union"
        ],
        "x-samchon-controller": "ExceptionController"
      }
    },
    "/exception/{section}/tags": {
      "post": {
        "tags": [],
        "parameters": [
          {
            "name": "section",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IBbsArticle.IStore"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IBbsArticle"
                }
              }
            }
          },
          "400": {
            "description": "invalid request",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "404": {
            "description": "unable to find the matched section",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "428": {
            "description": "unable to process the request",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "5XX": {
            "description": "internal server error",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        },
        "x-samchon-accessor": [
          "exception",
          "tags"
        ],
        "x-samchon-controller": "ExceptionController"
      }
    },
    "/exception/{section}/composite": {
      "post": {
        "tags": [],
        "parameters": [
          {
            "name": "section",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IBbsArticle.IStore"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IBbsArticle"
                }
              }
            }
          },
          "400": {
            "description": "invalid request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TypeGuardErrorany"
                }
              }
            }
          },
          "404": {
            "description": "unable to find the matched section",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/INotFound"
                }
              }
            }
          },
          "428": {
            "description": "unable to process the request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IUnprocessibleEntity"
                }
              }
            }
          },
          "5XX": {
            "description": "internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IInternalServerError"
                }
              }
            }
          }
        },
        "x-samchon-accessor": [
          "exception",
          "composite"
        ],
        "x-samchon-controller": "ExceptionController"
      }
    }
  },
  "components": {
    "schemas": {
      "IBbsArticle": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "title": {
            "type": "string",
            "minLength": 3,
            "maxLength": 50
          },
          "body": {
            "type": "string"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/IAttachmentFile"
            }
          }
        },
        "required": [
          "id",
          "created_at",
          "title",
          "body",
          "files"
        ]
      },
      "IAttachmentFile": {
        "type": "object",
        "properties": {
          "name": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "type": "string",
                "minLength": 1,
                "maxLength": 255
              }
            ]
          },
          "extension": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "type": "string",
                "minLength": 1,
                "maxLength": 8
              }
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "name",
          "extension",
          "url"
        ]
      },
      "IBbsArticle.IStore": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "minLength": 3,
            "maxLength": 50
          },
          "body": {
            "type": "string"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/IAttachmentFile"
            }
          }
        },
        "required": [
          "title",
          "body",
          "files"
        ]
      },
      "TypeGuardErrorany": {
        "type": "object",
        "properties": {
          "method": {
            "type": "string",
            "description": "The name of the typia method that threw this error."
          },
          "path": {
            "type": "string",
            "description": "The access path to the property where the assertion error occurred.\n\nUses dot notation to indicate the path for nested object properties.\nMay be `undefined` if the error occurred at the root level."
          },
          "expected": {
            "type": "string",
            "description": "String representation of the expected type at the error location.\n\nRepresents TypeScript types as strings, including detailed type information\nfor complex types."
          },
          "value": {
            "description": "The actual value that failed assertion.\n\nStores the actual value at the error path as-is.\nUseful for debugging by comparing the expected type with the actual value."
          },
          "name": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "stack": {
            "type": "string"
          }
        },
        "required": [
          "method",
          "expected",
          "value",
          "name",
          "message"
        ],
        "description": "Custom error class thrown when runtime assertion fails in `typia.assert<T>()` function.\n\nThis error is thrown by the `typia.assert<T>()` function when the input value\ndoesn't match the expected type.\n\nThe error provides detailed information about the first assertion failure encountered,\nincluding the access path where the error occurred, the expected type, and the actual value."
      },
      "INotFound": {
        "type": "object",
        "properties": {
          "schema": {
            "type": "string"
          },
          "table": {
            "type": "string"
          },
          "id": {
            "type": "string"
          }
        },
        "required": [
          "schema",
          "table",
          "id"
        ]
      },
      "IUnprocessibleEntity": {
        "type": "object",
        "properties": {
          "reason": {
            "type": "string"
          }
        },
        "required": [
          "reason"
        ]
      },
      "IInternalServerError": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "stack": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "name",
          "message",
          "stack"
        ]
      },
      "IExceptional.Something": {
        "type": "object",
        "properties": {
          "type": {
            "const": "something"
          }
        },
        "required": [
          "type"
        ]
      },
      "IExceptional.Nothing": {
        "type": "object",
        "properties": {
          "nothing": {
            "const": "nothing"
          }
        },
        "required": [
          "nothing"
        ]
      },
      "IExceptional.Everything": {
        "type": "object",
        "properties": {
          "everything": {
            "const": "everything"
          }
        },
        "required": [
          "everything"
        ]
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "apiKey"
      }
    }
  },
  "tags": [],
  "x-samchon-emended-v4": true
}